base: &base
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 50
  host: 127.0.0.1
  port: 3307
  username: root
  password: kenrome001

development:
  <<: *base
  database: rxy123

test:
  <<: *base
  database: rxy123

production:
  <<: *base
  database: rxy123